### ISSUE TITLE
Add SEO properties

### ISSUE THREAD

**Issue by vindective** [yii2-starter-kit/yii2-starter-kit#330]
### для сущностей
- Page
- Article

**Comment by Bropwnz0r** [comment]
It would be nice to add to all pages

**Comment by XzAeRo** [comment]
Which SEO properties should be added?

**Comment by Bropwnz0r** [comment]
Titles, Descriptions, Keywords, generate sitemap, and robots.txt

**Comment by Bropwnz0r** [comment]
Titles, Descriptions, Keywords - Should be taken from the translation files
