### ISSUE TITLE
Feature request: Swagger UI + generator for REST API documentation

### ISSUE THREAD

**Issue by remizyaka** [yii2-starter-kit/yii2-starter-kit#435]
Would be good to have some kind of API Doc generator  for rest api module

**Comment by XzAeRo** [comment]
This is a really good idea. But are there other alternatives to Swagger? I mean, if we will implement something like this in a project, we have to be fair with other alternatives.

**Comment by remizyaka** [comment]
Maybe RAML and  API Blueprint also. But swagger is quite good to start with.

**Comment by XzAeRo** [comment]
Yes, Swagger looks like the best alternative of all (also RAML has a plugin to import Swagger definitions).

**Comment by gouchaoer** [comment]
I really need more api feature such as swagger

**Comment by davidjeddy** [comment]
IMO, Swagger is the way to go.

**Comment by ignatenkovnikita** [comment]
I use [Swagger Module](https://github.com/ignatenkovnikita/yii2-swagger) realtime generator son

**Comment by davidjeddy** [comment]
@ignatenkovnikita Oh, thats nice. Will be giving that a try here soon.

**Comment by XzAeRo** [comment]
@ignatenkovnikita Really nice!

**Comment by alfredleo** [comment]
I am working on a project with swagger API support. I will try to create PR.

**Comment by XzAeRo** [comment]
Swagger docs implementation will be developed in the [`feature/swagger-docs`](
https://github.com/yii2-starter-kit/yii2-starter-kit/tree/feature/swagger-docs) branch if anyone wants to take a look or send PRs
