### ISSUE TITLE
Валидация изображений совместно с поведением

### ISSUE THREAD

**Issue by ASYOU99** [yii2-starter-kit/yii2-starter-kit#532]
Здравствуйте. Использую ваше сборку и столкнулся с таким вопросом если я использую ваше поведение UploadBehavior и одновременно пробую валидировать картинку в rules:
            ` ['thumbnail', 'image', 'extensions' => 'png, jpg, jpeg', 'message' => 'Не тот формат'],
            ['thumbnail', 'image', 'maxWidth' => 251, 'message' => 'Превышена ширина'],
            ['thumbnail', 'image', 'maxHeight' => 251, 'message' => 'Превышена высота'],`
То валидация не проходит ни по одному параметру. Не подскажите как совместить ваше поведения со стандартными валидаторами, у вас в классе есть только тип задать можно на сколько я понимаю    , а сам размер изображения нет (под размером подразумеваю не вес а высоту и ширину изображения)?

**Comment by trntv** [comment]
вообще UploadBehavior не навешивается на beforeValidate, так что на валидацию влиять не должен никак. `thumbnail` точно содержит `UploadedFile`?

**Comment by ASYOU99** [comment]
Я нашел решение но не знаю как прикрутить его в к поведению из за нехватки опыта может подскажите.
`public function actions(){
   return [
           'upload'=>[
               'class'=>'trntv\filekit\actions\UploadAction',
               'validationRules' => [
                        //тут правила
                        //https://github.com/yiisoft/yii2/blob/master/docs/guide/input-validation.md#ad-hoc-validation-
               ]
           ]
       ];
   }`

**Comment by trntv** [comment]
хм, вы все правильно сделали. Behavior и Action для совсем разных вещей предназначены. В Action правила указываются именно так

**Comment by ASYOU99** [comment]
Может я неправильно изначально делаю. Создал публичное св-во миниатюры и задал для него правила в рулсах. Пример загрузки взял у вас с статьи. Может нужно како йто кусок кода вам показать может где то что то недоделал или нетак написал?
