### ISSUE TITLE
Do we want to add IaaS examples?

### ISSUE THREAD

**Issue by davidjeddy** [yii2-starter-kit/yii2-starter-kit#604]
Using Terraform we could add examples of creating cloud provider agnostic configurations. One command creation of the application on the provider of choice. Thoughts?

**Comment by trntv** [comment]
awesome idea, simple starter template would be great!

**Comment by davidjeddy** [comment]
Glad you like the idea. Will work up a basic compute + database configuration.

**Comment by XzAeRo** [comment]
@davidjeddy would you work again on this issue? If not no problem :)

**Comment by davidjeddy** [comment]
Sadly I do not have the time in the foreseeable future.

**Comment by XzAeRo** [comment]
No problem! Thanks.
