### ISSUE TITLE
Support for official yiisoft/yii2-docker image

### ISSUE THREAD

**Issue by trntv** [yii2-starter-kit/yii2-starter-kit#609]

**Comment by davidjeddy** [comment]
Do we want to use the official yii2-docker-image as a base and leverage multi-step docker builds to apply the starter kit changes on top during build?

**Comment by trntv** [comment]
yes

**Comment by XzAeRo** [comment]
Recommended image: `yiisoftware/yii2-php:7.2-fpm`

Docs: https://github.com/yiisoft/yii2-docker

Example: https://github.com/yiisoft/yii2-app-basic/blob/master/docker-compose.yml
