### ISSUE TITLE
Strange behavior when email is not activated ("Re-send activation email" feature request)

### ISSUE THREAD

**Issue by deanpress** [yii2-starter-kit/yii2-starter-kit#633]
Currently if an email address is not activated, then:

1. User cannot login: Message: "This e-mail address is not found".
2. User cannot register new account. Message: "This e-mail address is already in use".

By default, the front-end should recognize when a user is trying to sign in to a non-activated account and give them the opportunity to request a new activation email.

**Comment by XzAeRo** [comment]
I tried reproducing this problem and I couldn't.

Also, users are "active" by default when they register, and the only possibility when I found when this won't happen, is when an admin or manager adds an user from the backend and set as "Not active", which is the desired behaviour.

Please provide more details and/or steps to reproduce the problem.

**Comment by deanpress** [comment]
@XzAeRo You need to enable email verification in `frontend/config/web.php` : 
```
    'modules' => [
        'user' => [
            'class' => frontend\modules\user\Module::class,
            'shouldBeActivated' => true
            ...
        ]
```
