### ISSUE TITLE
Error during startup using docker-compose per README.md

### ISSUE THREAD

**Issue by davidjeddy** [yii2-starter-kit/yii2-starter-kit#639]
Grabbed the latest master release 11fc1e20da43923adc6a45db8d4eed9c1f46a351

During the build / startup process I reviece an error about port 80 being in use.
```
test_machine:/trntv$ php --version
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
test_machine:/trntv$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
test_machine:/trntv$ php composer.phar run-script docker:start
> docker-compose up --force-recreate -d
Removing trntv_nginx_1
Recreating trntv_webpacker_1 ... 
Recreating trntv_webpacker_1
Recreating trntv_mailcatcher_1 ... 
Recreating trntv_db_1 ... 
Recreating trntv_db_1
Recreating trntv_db_1 ... done
Recreating trntv_app_1 ... 
Recreating trntv_app_1 ... done
Recreating 316db9733440_316db9733440_316db9733440_trntv_nginx_1 ... 
Recreating 316db9733440_316db9733440_316db9733440_trntv_nginx_1 ... error
ERROR: for 316db9733440_316db9733440_316db9733440_trntv_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint trntv_nginx_1 (95d3256e697327a5ca7238a2b0a56ac5cb46fdc2df8a0694796501a34cbde5d1): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint trntv_nginx_1 (95d3256e697327a5ca7238a2b0a56ac5cb46fdc2df8a0694796501a34cbde5d1): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
Encountered errors while bringing up the project.
Script docker-compose up --force-recreate -d handling the docker:start event returned with error code 1
test_machine:/trntv$ 
```

**Comment by XzAeRo** [comment]
Are you sure you don't have Nginx or Apache, or even other docker-application running in port 80 natively in your computer?

**Comment by davidjeddy** [comment]
Running `netstat -l` on my Ubuntu 18.04 I did not see anything on port 80. I'll double check tonight just to be sure.

**Comment by XzAeRo** [comment]
Everytime that the posted error appears, at least in my case, it's because I forgot to stop the nginx service.

Anyway, there is something weird with your installation... Docker outputs:

```
Recreating 316db9733440_316db9733440_316db9733440_trntv_nginx_1 ... 
```

When it should be just:

```
Recreating trntv_nginx_1 ... 
```

This may suggest that you have a orphaned nginx container that is kept up, and docker-compose just decided to rename it to avoid collisions.

If that's the case, make sure to run `docker-compose down` and  `docker-compose down --remove-orphans` inside the project folder, so all the previously created containers in the project get destroyed. Then you could run all the docker-compose commands to build the project.

**Comment by davidjeddy** [comment]
Agreed, the container name is weird. I did a `docker ps` and nothing was running; which lead me to reach out via this issue. I'll nuke all the containers (even stopped ones) and try a rebuild from scratch once I get home this evening.

**Comment by davidjeddy** [comment]
Yep, it was an Apache service running on port 80. :S Something installed it and I did not realize it. Everything looks well now....though having PHP installed on the host machine as a requirement kind of defeats the purpose of containerization...

![image](https://user-images.githubusercontent.com/6232455/47193103-2c91ce00-d31f-11e8-8aba-bf260adb4e16.png)


Anyways, all good now. Thank you.
