### ISSUE TITLE
 disable pjax for a view user link

### ISSUE THREAD

**Issue by dungmediabridge** [yii2-starter-kit/yii2-starter-kit#640]
![image](https://user-images.githubusercontent.com/41981016/47129815-0e958080-d2c1-11e8-88d8-5664481fa3a3.png)

**Comment by XzAeRo** [comment]
You should add the `data-pjax = "0"` property in the Html button. This is described in the Pjax documentation (in the description at the top): https://www.yiiframework.com/doc/api/2.0/yii-widgets-pjax

In the case of the Timeline, it would be something like:

```php
<?php echo \yii\helpers\Html::a(
    Yii::t('backend', 'View user'),
    ['/user/view', 'id' => isset($model->data['user_id']) ? $model->data['user_id'] : $model->data['userId']],
    ['class' => 'btn btn-primary btn-flat btn-xs', 'data-pjax' => 0],
) ?>
```
