### ISSUE TITLE
An outdated code when installing via composer

### ISSUE THREAD

**Issue by nikosid** [yii2-starter-kit/yii2-starter-kit#641]
If I install the application as descibed in README I get some outdated files. For example if we open `PageSearch.php` we see the namespace is `\backend\models\search` but file is located in `backend\modules\content\models\search` and the same is in `\backend\modules\content\controllers\PageController` with the `PageSearch` namespace.

**Comment by trntv** [comment]
I've tagged a new release. It will fix the problem.
