### ISSUE TITLE
Class db does not exist при тестировании

### ISSUE THREAD

**Issue by alien-art** [yii2-starter-kit/yii2-starter-kit#645]
Не получается запустить функциональные тесты, все валится на этапе загрузки фикстур ФикстурХелпером
```
Instance.php line 139:

  Failed to instantiate component or class "db".


In Container.php line 428:

  Class db does not exist
```

Не понятно чего ему не хватает

**Comment by XzAeRo** [comment]
Related to https://github.com/yiisoft/yii2/issues/15478
