### ISSUE TITLE
hide frontend/web and backend/web to admin

### ISSUE THREAD

**Issue by minhtruong1993** [yii2-starter-kit/yii2-starter-kit#656]
How to hide the frontend / web and turn the backend / web into admin.
Hope the helping

**Comment by XzAeRo** [comment]
Can you elaborate a little bit more? I'm not sure what you want to do... do you want to hide the folders? Or make them restricted only for `webmaster` access levels?

**Comment by dinya17** [comment]
I have the same question
 I want to hide from URL  
frontend/web
backend/web

I just want to have 
host::port/article/111
host::port**/admin/**timeline-event/index

but i always have 
**/backend/web//**timeline-event/index



i am using nginx config file 
and
SINGLE DOMAIN INSTALLATION

https://github.com/yii2-starter-kit/yii2-starter-kit/blob/master/docker/nginx/vhost_single_domain.conf

and 
.env
FRONTEND_BASE_URL     = /
BACKEND_BASE_URL      = /backend/web/
STORAGE_BASE_URL     = /storage/web

IF i am trying  to change  config like here
'components'=>[
        ...
        'request' => [
            'baseUrl' => '/admin',
        ...

a im have
Not Found (#404)
