### ISSUE TITLE
index-test.php vulnerability

### ISSUE THREAD

**Issue by deanpress** [yii2-starter-kit/yii2-starter-kit#658]
If `frontend/web/index-test.php`is left available in a production server, anyone can constantly load `FRONTEND_URL /index-test.php` and cause a ddos due to resource intensivity.

**Comment by rivieiraa** [comment]
From `frontend/web/index-test.php`

<?php
require(__DIR__ . '/../../tests/bootstrap.php');

// NOTE: Make sure this file is not accessible when deployed to production
if (YII_ENV !== 'test') {
    die('You are not allowed to access this file.');
}

You can't ddos with YII_ENV === 'prod'

**Comment by deanpress** [comment]
The issue most likely came from `require(__DIR__ . '/../../tests/bootstrap.php');`. We were definitely in production mode. I'll have to find the exact commit on our end.

**Comment by rivieiraa** [comment]
Just checked. Problem actually exists and it's caused by /tests/bootstrap.php file.

#661

**Comment by XzAeRo** [comment]
Thank you!
