### ISSUE TITLE
Добавление языка в адресную строку

### ISSUE THREAD

**Issue by aleksandrhorkavyi** [yii2-starter-kit/yii2-starter-kit#659]
Добрый день, подскажите пожалуйста, можно ли изменить настройки преложения чтобы в адресной строке отображался выбранный язик, например, http://starter-kit/en/page/about вместо http://starter-kit/page/about ?

**Comment by rivieiraa** [comment]
Нет, нельзя. Настройки языка сохраняются в куки.
Копайте тут [https://github.com/yii2-starter-kit/yii2-starter-kit/blob/master/common/behaviors/LocaleBehavior.php](url)
