### ISSUE TITLE
Update to AdminLTE 3 and Bootstrap 4

### ISSUE THREAD

**Issue by XzAeRo** [yii2-starter-kit/yii2-starter-kit#662]
https://adminlte.io/themes/AdminLTE/pages/layout/top-nav.html

Should we implement this design in the frontend application instead of the basic Bootstrap design?

I added the branch `feature/adminlte-frontend` if anyone wants to take a look at the codebase changes.

![screenshot_2019-01-21 yii2 starter kit](https://user-images.githubusercontent.com/1656037/51487692-69d48480-1d82-11e9-9182-5d4be0a2fa68.png)

**Comment by kwazaro** [comment]
There will be AdminLTE3 on Bootstrap 4 soon, maybe we should wait some time and then switch to new AdminLTE and Bootstrap 4 with gulp/webpack for full kit?

**Comment by XzAeRo** [comment]
AdminLTE 3 with Bootstrap 4 is finally in stable releases.

Will start a new branch for this issue really son.

**Comment by XzAeRo** [comment]
Please follow #745 for updates.
