### ISSUE TITLE
Access denied for user ysk_dbu when docker build

### ISSUE THREAD

**Issue by Tpona** [yii2-starter-kit/yii2-starter-kit#665]
Hi there!
When i build docker image i get this error:

<img width="1328" alt="2019-01-29 9 07 37" src="https://user-images.githubusercontent.com/6121024/51887570-62763200-23a5-11e9-84ae-692239a631ea.png">

What i doing wrong?

**Comment by XzAeRo** [comment]
You're not doing nothing wrong. You're probably running `composer docker:build` or `composer run-script docker:build` right?

There's a missing `wait` command in the composer script, which should prevent running the `app/setup` command before the database container has been fully started by docker.

**Comment by XzAeRo** [comment]
Fix added under `develop` branch
