### ISSUE TITLE
Security issues with npm modules

### ISSUE THREAD

**Issue by alfredleo** [yii2-starter-kit/yii2-starter-kit#669]
Github showed that there are 4 security issues with npm modules.
1. cryptiles • package-lock.json high severity
2. macaddress • package-lock.json critical severity
3. sshpk • package-lock.json moderate severity
4. hoek • package-lock.json moderate severity
How should we treat them? They are npm modules so is there a real issue?
![screenshot_3](https://user-images.githubusercontent.com/4072844/52949450-1d3e9200-339e-11e9-88bb-e692a6a1ee64.png)

**Comment by XzAeRo** [comment]
It's not really an issue since we are not using them in production anyway, but it doesn't hurt to fix it...

I just fixed the culprit packages with `npm audit fix` and bumped the `less` package to the latest one (since this one was the biggest offender).

Thanks for the heads up!
