### ISSUE TITLE
Translation module conflict with Indonesian language

### ISSUE THREAD

**Issue by jdme** [yii2-starter-kit/yii2-starter-kit#670]
There is conflict in **translation** module with Indonesian language. It has **ISO code "id"** which is the same as **primary key** of Source model.

I got error in browser:
> PHP Notice – yii\base\ErrorException
> Undefined property: backend\modules\translation\models\Source::$id

At this line it gets relation instead of primary key:
https://github.com/yii2-starter-kit/yii2-starter-kit/blob/36633148718a4f1e237ccf0e9c1154c62bab00c7/backend/modules/translation/models/Source.php#L57

**Comment by alfredleo** [comment]
Please describe the error. Where does it happen? Describe the steps you did to get to this error. 
Tests did not show any error. 
![image](https://user-images.githubusercontent.com/4072844/53337461-4a9db980-3923-11e9-8d35-f73d28d77d2c.png)

**Comment by jdme** [comment]
This error appears, when you are at backend translation page:
1. Go to http://backend.yii2-starter-kit.localhost/translation/default/index.
2. Add some source message, if it isn't there. And you got error.

Some screenshots:
![deepinscreenshot_ - _20190226172357](https://user-images.githubusercontent.com/2732162/53416202-6751f400-39ec-11e9-9097-b8d090407412.png)
![deepinscreenshot_ - _20190226172328](https://user-images.githubusercontent.com/2732162/53416206-67ea8a80-39ec-11e9-9363-f00bf1120213.png)
![deepinscreenshot_ - _20190226172213](https://user-images.githubusercontent.com/2732162/53416207-691bb780-39ec-11e9-8c51-f85e12f37a65.png)

**Comment by XzAeRo** [comment]
Ok, so let's clear out some things:

* You already added "Indonesian (id)", to `@common/config/base.php`.
* Did you also added the code to `@common/config/messages/_base.php`? There's a "`languages`"array that needs to contain the language codes available in `_base.php`.
* Did you run `console/yii message/extract @common/config/messages/db.php` to migrate the translation codes to the database?

**Comment by XzAeRo** [comment]
Oh I just noticed that you're trying to use PHP Message Source files... The backend translation modules has nothing to do with that, it's only used when you're using DB Message Source.

Anyway, the questions remain almost the same:

* You already added "Indonesian (id)", to `@common/config/base.php`.
* Did you also added the code to `@common/config/messages/_base.php`? There's a "`languages`"array that needs to contain the language codes available in `@common/config/base.php`.

**Comment by jdme** [comment]
>    Did you also added the code to `@common/config/messages/_base.php`? There's a "`languages`"array that needs to contain the language codes available in `@common/config/base.php`.

The existence of source messages in DB doesn't impact on this issue, as well as current message source set in config.

Anyway, I extracted messages to DB as you suggested:
>    console/yii message/extract @common/config/messages/db.php

Also I added some translation to database manually (from mysql client), so it appears on web page. It means the translation itself works fine. 

But if I go to http://backend.yii2-starter-kit.localhost/translation/default/index, there is an error.
So this issue is only about the **CRUD translation module** in backend, not about translation itself.

**Comment by XzAeRo** [comment]
But you need too add the language in the array in `@common/config/messages/_base.php` also.

Otherwise is not going to work.

**Comment by jdme** [comment]
> 

> But you need too add the language in the array in `@common/config/messages/_base.php` also.
> 
> Otherwise is not going to work.

It's already there. I added.

**Comment by XzAeRo** [comment]
>It's already there. I added.

Ok, good, I will check it later and see what comes out of this. Thanks for reporting!

**Comment by XzAeRo** [comment]
Hey, so I checked what you posted and I think I figured out the issue.

The thing is, the translation module of the backend is intended to be used only when you're using `DbMessageSource` as translation component. 

`yii\base\ErrorException: Undefined property: backend\modules\translation\models\Source::$id` is basically saying, "I can't find this attribute on the database". Which is correct since the table for the translations is not defined!

So, what's next? If you want to use `DbMessageSource`, go to `common/config/base.php` and uncomment the code about `DbMessageSource`, and also **comment or delete the `PhpMessageSource`** component configuration. Otherwise `PhpMessageSource` will be used.

Let me know if you keep struggling with the translations issue, but on the meantime, I will put some code to disable the translations module in the backend if the `DbMessageSource` is not active.

**Comment by XzAeRo** [comment]
Now, when trying to look at the translation module without the DbMessageSource component enabled, you'll be greeted with this message.
![screenshot_2019-03-01 conflict 409](https://user-images.githubusercontent.com/1656037/53670536-d4b68c80-3c59-11e9-8dcc-aab3fdbb206b.png)

**Comment by jdme** [comment]
> The thing is, the translation module of the backend is intended to be used only when you're using `DbMessageSource` as translation component.
> 
> `yii\base\ErrorException: Undefined property: backend\modules\translation\models\Source::$id` is basically saying, "I can't find this attribute on the database". Which is correct since the table for the translations is not defined!

This is false conclusion. Translation table is defined by default.
In our case the message `yii\base\ErrorException: Undefined property: backend\modules\translation\models\Source::$id` is saying "I want to get the primary key, which is *$id*, but I get the translation for Indonesian language instead, which has language code *id*, and it is not defined".

As I mentioned earlier, the problem is here:
https://github.com/yii2-starter-kit/yii2-starter-kit/blob/36633148718a4f1e237ccf0e9c1154c62bab00c7/backend/modules/translation/models/Source.php#L57

To fix this issue I made some changes locally. I suggest these changes as a PR now. You decide to merge it or refactor somehow. My workaround is using prefixes for "virtual language properties" in *Source* and *SourceSearch* models.

I think restricting access to the module is cutting it's convinience. More flexible if developer decide when to restrict or not. Better to reverse this changes.
