### ISSUE TITLE
Does not attach more than 2 files

### ISSUE THREAD

**Issue by AScarj** [yii2-starter-kit/yii2-starter-kit#675]
After a clean installation, I create an article, add attached files, but after saving, only 2 files (images) are added.

The file limit is 10 pieces, the file size does not exceed the maximum allowed.

All files are successfully added to storage and displayed in the panel. But only 2 files are attached to the article. Moreover, when adding several files again, it replaces only the last file.

![image](https://user-images.githubusercontent.com/30417116/53786259-f73bf480-3f3c-11e9-9165-c96842f72992.png)

**Comment by rivieiraa** [comment]
#146

**Comment by AScarj** [comment]
In this thread there is no solution to the problem.
The problem is observed in a clean installation, without my modifications.

**Comment by rivieiraa** [comment]
Which version of yii2-starter-kit/yii2-file-kit do you have in that fresh installation ?

**Comment by AScarj** [comment]
Just made another new install.
Pre update composer
The problem has disappeared. Which is strange, since I have already done 3 clean installs on 2 different computers.
Perhaps the problem was in some old file.

Sorry, problem fixed. You can close.

![image](https://user-images.githubusercontent.com/30417116/53804957-b2c74d80-3f6a-11e9-86e7-bc1e4034c585.png)
