### ISSUE TITLE
install new packet does not working - composer

### ISSUE THREAD

**Issue by AngelDios** [yii2-starter-kit/yii2-starter-kit#678]
hello, I have a problem wanting to install a new package, when I try to install or update I get an error related to the lack of dependencies, and tried to update the composer.json but after 3 hours it shows the following error.

![image](https://user-images.githubusercontent.com/28678385/55135131-bfb60780-50f8-11e9-975c-b70f836d18b8.png)

![image](https://user-images.githubusercontent.com/28678385/55134121-e6bf0a00-50f5-11e9-903a-6c9ae252da85.png)

packet: "kartik-v/yii2-widget-select2": "dev-master"

with `composer diagnose` sample

![image](https://user-images.githubusercontent.com/28678385/55134817-e3c51900-50f7-11e9-92e5-3c9f126c2fce.png)

Any suggestions to solve this problem and install new packages ?

**Comment by AngelDios** [comment]
I found the solution to the problem, it was because of a corrupt composer installation, I had to reinstall it to solve the problem.

**Comment by rivieiraa** [comment]
@AngelDios good to hear it's not about the code 👍
