### ISSUE TITLE
Class fileStorage does not exist

### ISSUE THREAD

**Issue by tanghienphong** [yii2-starter-kit/yii2-starter-kit#680]
I downloaded this source and setup in my project. After finishing and go to test. But there are some error when I upload a file with the wiget - "Class fileStorage does not exist". I can not fix this. Please help me. Thank All!

**Comment by rivieiraa** [comment]
Question needs more clarity.
How actually did you install strater kit?
What file causes this error to popup?

Any stack trace?

**Comment by tanghienphong** [comment]
Hello rivieiraa,
I installed via Yii2-file-kit, I copied the modules file and changed the namespaces. In the View.php, I call the Upload Wiget with that code:
`<?php
use trntv\filekit\widget\Upload;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>
<div class="demo-index box box-primary">
    <div class="box-header"></div>
    <div class="box-body">
        <?php
        $form = ActiveForm::begin([
                    'enableClientValidation' => false,
                    'enableAjaxValidation' => true,
        ]);
        ?>
        <?php
        echo $form->field($model, 'name')->widget(
                Upload::class, [
            'url' => ['/file/storage/upload'],
            'maxFileSize' => 5000000, // 5 MiB
        ]);
        ?>
        <?php ActiveForm::end() ?>
    </div>
</div>
`
After that, I try to test the example, and make a mistake. Some error like the attachment.
![error-1](https://user-images.githubusercontent.com/33262045/55714731-5ea60200-5a1d-11e9-9e08-d8c6634d49cf.png)
![error-2](https://user-images.githubusercontent.com/33262045/55714733-5f3e9880-5a1d-11e9-8fdf-46418ed45ed2.png)
![error-3](https://user-images.githubusercontent.com/33262045/55714734-5f3e9880-5a1d-11e9-9f4b-59312fbd4f48.png).
Thanks for your help!

**Comment by tanghienphong** [comment]
![error-1](https://user-images.githubusercontent.com/33262045/55714815-8b5a1980-5a1d-11e9-9541-3dbde3b31dae.png)

**Comment by rivieiraa** [comment]
So, what was the reason ? :)
