### ISSUE TITLE
how to call the upload widget by js

### ISSUE THREAD

**Issue by exploradatos** [yii2-starter-kit/yii2-starter-kit#681]
How are you ! , someone tells me how I can call the upload widget by js.
I'm newly using yii2-starter-kit, I really do not know how to call this widget by js.

For example with kartik widgets I use them in the following way.

JS
```
$("#plus").inputmask({
            "alias":"decimal",
            "groupSeparator":".",
            "digits":1,
            "integerDigits":2,
            "autoGroup":true,
            "removeMaskOnSubmit":true,
            "rightAlign":false,
            "allowMinus":false,
            "max":20.0,
            "min":0.1,
        });
```

but with the upload widget that uses yii2-starter-kit I do not know how to do it, can someone help me with this problem?

**Comment by rivieiraa** [comment]
Upload widget based on BlueImp file upload widget. Read the docs [here](https://github.com/yii2-starter-kit/yii2-file-kit)

Btw, issues feature actually made to point to some errors / problems, but not in educational purposes ;-)

**Comment by XzAeRo** [comment]
What @rivieiraa says should lead you in the right path.

As a word of advice, please refrain from using the widget directly via javascript. You can manipulate the widget almost completely via parameters, such as the `clientOptions` parameter:

```php
\trntv\filekit\widget\Upload::widget([
    'model' => $model,
    'attribute' => 'files',
    'url' => ['upload'],
    'uploadPath' => 'subfolder', // optional, for storing files in storage subfolder
    'sortable' => true,
    'maxFileSize' => 10 * 1024 * 1024, // 10Mb
    'minFileSize' => 1 * 1024 * 1024, // 1Mb
    'maxNumberOfFiles' => 3 // default 1,
    'acceptFileTypes' => new JsExpression('/(\.|\/)(gif|jpe?g|png)$/i'),
    'showPreviewFilename' => false,
    'clientOptions' => [ ...other blueimp options... ]
]);
```

**Comment by exploradatos** [comment]
Can you give me an example using `clientOptions` to call the upload without using javascript ?
