### ISSUE TITLE
docker installation doesn't work

### ISSUE THREAD

**Issue by jer1k** [yii2-starter-kit/yii2-starter-kit#707]
Recently, the installation as a docker began to crash.
I get a warning when checking:

> 
> configure: WARNING: ============================================== ==========
> configure: WARNING: Use of bundled libzip is deprecated and will be removed.
> configure: WARNING: Some features such as encryption and bzip2 are not available.
> configure: WARNING: Use system library and --with-libzip is recommended.
> configure: WARNING: ============================================== ==========

There are also some errors when compiling.

as a result, we have an error:
`Script docker-compose up --force-recreate -d handling the docker:start event returned with error code 1`

I tried on two different VPS with different versions of the docker and after the failure I tried on my desktop - the result is the same.

**Comment by rivieiraa** [comment]
Try changing line endings from windows CRLF to unix LF in docker/php/install-composer.sh file and re-run docker-compose. I had the same error not so far ago.

**Comment by alfredleo** [comment]
This is the fix https://github.com/yii2-starter-kit/yii2-starter-kit/pull/734

**Comment by XzAeRo** [comment]
A new update fixes this issue. If you are experiencing this issue, please update to the latest version of the project.
