### ISSUE TITLE
php composer.phar require --prefer-dist illusion/yii2-excel "*"  failed

### ISSUE THREAD

**Issue by yunfeiboy** [yii2-starter-kit/yii2-starter-kit#709]
php composer.phar require --prefer-dist illusion/yii2-excel "*"  failed，
never succeeded.
i cant's install new components,why?rm composer.lock?

**Comment by rivieiraa** [comment]
Need more details.
Paste here error log please

**Comment by yunfeiboy** [comment]
rm composer.lock
composer install
Result：
 [Composer\Downloader\TransportException]                                      
  The "https://repo.packagist.org/p/provider-2015%24f38b0947c29fab0d87788e8b1d5c60a70f2c4e342bf114d8308ce36343b6f87c.
  json" file could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by rivieiraa** [comment]
What i found out is that json file composer points to really does not exist. BUT:
I tried to install package and had no errors:

```
composer require illusion/yii2-excel --no-plugins
Using version ^1.2 for illusion/yii2-excel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing markbaker/matrix (1.1.4): Downloading (100%)
  - Installing markbaker/complex (1.4.7): Downloading (100%)
  - Installing phpoffice/phpspreadsheet (1.8.2): Downloading (100%)
  - Installing illusion/yii2-excel (v1.2.5): Downloading (100%)
phpoffice/phpspreadsheet suggests installing mpdf/mpdf (Option for rendering PDF with PDF Writer)
phpoffice/phpspreadsheet suggests installing dompdf/dompdf (Option for rendering PDF with PDF Writer)
phpoffice/phpspreadsheet suggests installing tecnickcom/tcpdf (Option for rendering PDF with PDF Writer)
phpoffice/phpspreadsheet suggests installing jpgraph/jpgraph (Option for rendering charts, or including charts with PDF or HTML Writers)
```

Try installing phpoffice/phpspreadsheet package separately and see what happens.

**Comment by yunfeiboy** [comment]
I try
composer require illusion/yii2-excel --no-plugins
It succeeded,The result is the same as yours,I can have a pleasant code. Thank you!

**Comment by rivieiraa** [comment]
@XzAeRo we're done here :)
