### ISSUE TITLE
Composer report exception wher

### ISSUE THREAD

**Issue by shining228** [yii2-starter-kit/yii2-starter-kit#710]
After I create project, enter the project, run composer update, I got an exception like below, how to handle this? thx!
![image](https://user-images.githubusercontent.com/4729917/63486837-ad8b9a00-c4db-11e9-9197-270468d49e21.png)

**Comment by shining228** [comment]
Btw, create project is just fine

**Comment by XzAeRo** [comment]
This seems like a one-time error.

Does it keeps happening?
