### ISSUE TITLE
create new roles and permissions - RBAC

### ISSUE THREAD

**Issue by exploradatos** [yii2-starter-kit/yii2-starter-kit#711]
Hi, have a question about creating own permissions and roles, I try to add new ones but they don't work for , rather I realize that the on `backend/config/web.php` has default roles, I want to know if it is possible eliminate the default ones and create own.

**Comment by rivieiraa** [comment]
There are default roles, but entrie project is only a template. Modify it to suit your needs.

Use RBAC migrations to manage roles.
[Documentation link](https://www.yiiframework.com/doc/guide/2.0/en/security-authorization#using-migrations)

**Comment by rivieiraa** [comment]
If you're on developing stage of project / need fixed roles then i recommend to stick to migrations. But if you develop project that involves creation of roles by administrator it may be better choice to create roles through UI.

**Comment by exploradatos** [comment]
Excellent, then I will start by modifying according to the RBAC manual.  Thanks for dispelling the doubt.
