### ISSUE TITLE
many problems with new composer packets

### ISSUE THREAD

**Issue by dragun007** [yii2-starter-kit/yii2-starter-kit#712]
I am trying on 4 different computers(win7, win10 and debian) in 3 different network.

I am going in new folder and run this
composer create-project yii2-starter-kit/yii2-starter-kit myproject.com --ignore-platform-reqs
сd myproject.com/
composer require 2amigos/yii2-taggable-behavior:~1.0 --prefer-dist --profile

It works always run around 15-30 mins, and often gets github api limit(5000 per hour).

Only on one computer in win7 it finished without errors(other get on different packet different errors like 404 or 500).

if I run the commands separately, it works fine.

Today i test this:
composer require philippfrenzel/yii2fullcalendar "*"
and wait another 20 min and get api limit)on debian)

I think problems with bower
Sample profile log first command:
https://cdn.discordapp.com/attachments/398467906066841602/606874424230281216/unknown.png

on other computer i get this error:
[Composer\Downloader\TransportException]
  The "http://packagist.org/p/npm-asset/underscore%24a2a03d456cfff5bc8725b417
  de64a8d8455b6783db824c4f338e3ce09622a005.json" file could not be downloaded
   (HTTP/1.1 302 Found)

**Comment by dragun007** [comment]
after rate limit i put new token in command line, but only one time it finished. But i think it not good get so many request and waiting around half hour

**Comment by XzAeRo** [comment]
Try running your composer commands with `--no-plugins`.

Yii2 (and this project also), used to resolver bower and npm dependencies with the `fxp/composer-asset-plugin` plugin package installed globally. Now, there's a repository configured in the `composer.json`, that resolves those dependencies without the need for a plugin.

Let me know if it works for you.

**Comment by dragun007** [comment]
Thanks a lot. It helps me.
