### ISSUE TITLE
Composer always failed when I am using this repo

### ISSUE THREAD

**Issue by cougar999** [yii2-starter-kit/yii2-starter-kit#721]
Thanks for your amazing work first.
I used this on one of my projects, it's very handy. But there is one pain for me, every time I want to install a new extension, I need to add them manually, because it always failed if I install extensions by the composer.  

It takes a very long time to verify and install packages, then it gives an error. If I install the extensions in an empty folder, the composer runs very fast and successful.

Is there any way to fix this composer installation issue? Thanks

**Comment by rivieiraa** [comment]
Read this one https://github.com/yii2-starter-kit/yii2-starter-kit/issues/712

**Comment by cougar999** [comment]
Cool, this resolved the issue.
