### ISSUE TITLE
Single authorization for backend and frontend

### ISSUE THREAD

**Issue by AScarj** [yii2-starter-kit/yii2-starter-kit#728]
Tell me how to make a single authorization for the backend and frontend. 
Changing the cookieValidationKey does not solve the problem, since different models are used for the user.

**Comment by XzAeRo** [comment]
You should change these lines so they use the same cookie validation key and base URL:

https://github.com/yii2-starter-kit/yii2-starter-kit/blob/master/frontend/config/web.php#L50
https://github.com/yii2-starter-kit/yii2-starter-kit/blob/master/backend/config/web.php#L11

**Comment by dungphanxuan** [comment]
@AScarj can you set session for frontend https://github.com/dungphanxuan/yiiviet.name.vn/blob/master/frontend/config/web.php#L59
