### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by awais-vteams** [yii2-starter-kit/yii2-starter-kit#730]
While latest cloning and `composer update` got error

```
  [UnexpectedValueException]                                                              
  Could not parse version constraint >=1.1.0,,<2.0: Invalid version string "1.1.0,,<2.0"  
```

**Comment by awais-vteams** [comment]
![image](https://user-images.githubusercontent.com/10154558/69135288-b55ada80-0ada-11ea-8b09-5fadbbbc6c4a.png)

**Comment by rivieiraa** [comment]
Check your composer.json for this fragment `1.1.0,,<2.0` . It's not valid version declaration

**Comment by awais-vteams** [comment]
@rivieiraa composer.json is the same as https://github.com/yii2-starter-kit/yii2-starter-kit/blob/master/composer.json
I have just downloaded a fresh clone and trying to install it. My composer version is latest `1.9.1`

**Comment by rivieiraa** [comment]
First of all, if you're making fresh install you have to run `composer install` not `update`, you may add `--no-plugins` if you still have issues.

**Comment by awais-vteams** [comment]
Thanks `composer install` works.
