### ISSUE TITLE
Storage type xss exists in the background

### ISSUE THREAD

**Issue by wind226** [yii2-starter-kit/yii2-starter-kit#731]
step1：
access：http://backend.yii2-starter-kit.terentev.net/content/page/index
Click![image](https://user-images.githubusercontent.com/24953996/69221777-0938f280-0bb3-11ea-812f-3f441e5d62ef.png)
Fill in：xss payload
The last plugin that triggers xss
![image](https://user-images.githubusercontent.com/24953996/69221800-1950d200-0bb3-11ea-9715-6a2436bade48.png)
![image](https://user-images.githubusercontent.com/24953996/69221846-308fbf80-0bb3-11ea-952a-091321550a8c.png)

**Comment by XzAeRo** [comment]
Oof, big yikes.

In general this should be not much of a concern, since modifying pages/article data is behind authentication anyway, but we will have to take a look into this anyway. Not good.

Thanks for the report!
