### ISSUE TITLE
Docker without composer && docker for windows CRLF LF 

### ISSUE THREAD

**Issue by chemiu** [yii2-starter-kit/yii2-starter-kit#735]
Hi all
Thanks for this
I would like to suggest that since this is a docker installation, users should not need to have anything else besides docker, specifically composer. 

in addition windows is notorious for it's installation scripts problems relating to CRLF .
[solution here](http://www.devops-blog.net/docker/advice-on-building-docker-images-on-windows)

**Comment by XzAeRo** [comment]
Composer image should be added really soon.

Thanks for the tip about composer scripts on Windows.
