### ISSUE TITLE
Composer тормозит

### ISSUE THREAD

**Issue by vdstud** [yii2-starter-kit/yii2-starter-kit#736]
Почему при установке дополнений в yii2-starterr-kit "updating dependencies" занимает часы? В других проектах composer работает нормально. Убирал composer.json, composer.lock, ничего не меняется. Что я не так делаю?

**Comment by rivieiraa** [comment]
composer install -no-plugins стоит попробовать

**Comment by vdstud** [comment]
Спасибо за ответ. После выполнения "composer global remove fxp/composer-asset-plugin" все наладилось.
