### ISSUE TITLE
Avatar upload not working when using flysystem. Error in saved path

### ISSUE THREAD

**Issue by pcalafatich** [yii2-starter-kit/yii2-starter-kit#740]
Avatar is saved in http://DOMAIN/storage/source//1/IMAGE_NAME.jpg and it must be in http://DOMAIN/storage/web/source/1/IMAGE_NAME.jpg

**Comment by XzAeRo** [comment]
No, this is the correct behaviour. Your server configuration should be serving files from `web` folder in the storage.

The root for the storage should be `/path/to/project/storage/web`.

If you are using single domain setup, please make sure to change that.
