### ISSUE TITLE
In docker environment generated migrations are owned by root and can't be modified by linux user.

### ISSUE THREAD

**Issue by thecodeholic** [yii2-starter-kit/yii2-starter-kit#763]
I have the project setup using docker. When I generate new migration by executing `docker-compose exec app console/yii migrate` it creates migration file in `common/migrations/db` folder, but it is owned by root, however my PHPStorm is running with non root user and I can't modify the migration file anymore.

The solution is of course run `chown` command everytime when you generate new migration, but it's not good solution.

Do you have any idea?

**Comment by XzAeRo** [comment]
Yes, this is due to some shenanigans with docker. See: #696
