### ISSUE TITLE
Would you consider Ansible version of project set up?

### ISSUE THREAD

**Issue by senguttuvang** [yii2-starter-kit/yii2-starter-kit#765]
Here, I have set up the project in vagrant through Ansible in Ubuntu/Nginx. Would you consider them to be included in Wiki? If you require specific changes, I'd be happy to do it.

https://github.com/PearlThoughts/Yii2-Starter-Kit-Nginx-Setup

**Comment by XzAeRo** [comment]
That would be awesome!

Let me know if you need any input or help with that.

**Comment by senguttuvang** [comment]
Glad that you are interested. That is already done and verified on my laptop. Shall we move this repo to your Organisation and reference it in the Installation manual so people can check it?

**Comment by trntv** [comment]
Hi, thanks for your intereset, but Vagrant
